#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# CHECK THE PATH
#=================================================

# Normalize the URL path syntax
path_url=$(ynh_normalize_url_path $path_url)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# Backup the current index
cp "$final_path/index.html" "$final_path/index.html.back"
# Download, check integrity, uncompress and patch the source from build.src
ynh_setup_source "$final_path" build
# Then replace the index to keep the last modified links
mv "$final_path/index.html.back" "$final_path/index.html"

# Download, check integrity, uncompress and patch the source from cd_build.src
ynh_setup_source "$final_path/cd_build" cd_build

#=================================================
# NGINX CONFIGURATION
#=================================================

# Create a dedicated nginx config
if [ "$path_url" != "/" ]
then
	ynh_replace_string "^#sub_path_only" "" "../conf/nginx.conf"
fi
ynh_add_nginx_config

#=================================================
# CREATE DEDICATED USER
#=================================================

# Create a system user
ynh_system_user_create $app

#=================================================
# SPECIFIC UPGRADE
#=================================================
# ADD A CRON FILE
#=================================================

echo "0 2 * * * root \"$final_path/cd_build/auto_build.sh\" > /dev/null 2>&1" > /etc/cron.d/$app

#=================================================
# MODIFY VARIABLE IN AUTO_BUILD SCRIPT
#=================================================

ynh_replace_string "^build_yunohost_org_dir=.*" "build_yunohost_org_dir=\"$final_path\"" "$final_path/cd_build/auto_build.sh"
ynh_replace_string "^iso_directory=.*" "iso_directory=\"$final_path\"" "$final_path/cd_build/auto_build.sh"

#=================================================
# PATCH BUILD-YUNOHOST SCRIPT
#=================================================

# build-simple-cdd can't be run by root
ynh_replace_string "build-simple-cdd" "sudo -u $app build-simple-cdd" "$final_path/cd_build/build-yunohost"

#=================================================
# UPDATE THE PATH IN INDEX.HTML
#=================================================

ynh_replace_string "https://build.yunohost.org" "https://$domain${path_url%/}" "$final_path/index.html"

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
chown -R $app: $final_path

#=================================================
# SETUP LOGROTATE
#=================================================

mkdir -p /var/log/$app
# Replace the destination of the log
ynh_replace_string "\$script_dir/ynh_build.log" "/var/log/$app/ynh_build.log" "$final_path/cd_build/auto_build.sh"
# Use logrotate to manage application logfile
ynh_use_logrotate --non-append

#=================================================
# SETUP SSOWAT
#=================================================

ynh_app_setting_set $app skipped_uris "/"

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
